server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024
  tomcat:
    uri-encoding: utf-8
  port: 8080

spring:
  application:
    name: EncBox-Web
  servlet:
    multipart:
      enabled: false
      max-file-size: 2048MB
      max-request-size: 10240MB

eureka:
  client:
    enabled: false
